# configs/pretrain.yaml

# Model
backbone_name: resnet18
# backbone_name: mobilenet_v3_large
output_dim: 8

# Input
image_size: 224

# Dataset
datasets:
  # - name: oxford_pets
  #   sampling: 0.1
  #   weight: 1.0
  - name: midv2020
    sampling: 0.1
    weight: 2.0
  - name: smartdoc
    sampling: 0.1
    weight: 3.0

valid_split: 0.1
seed: 42

# DataLoader
batch_size: 16
num_workers: 8

# Loss
loss:
  name: CombinedLoss
  wing_w: 10.0
  wing_epsilon: 2.0
  lambda_iou: 0.5

# Optimizer
optimizer:
  name: AdamW
  backbone_lr: 2.0e-4
  head_lr: 2.0e-4
  weight_decay: 1.0e-5

# Scheduler
scheduler:
  name: StepLR
  step_size: 10
  gamma: 0.5

# Training
freeze_backbone: false
max_epoch: 100
patience: 10
monitor: loss
mode: min